---
  # tasks file for nextcloud
  - name: Create a directory if it does not exist
    file:
      path: /home/ansible/uproot-nextcloud
      state: directory
  - name: Create a directory if it does not exist
    file:
      path: /home/ansible/uproot-nextcloud/nginx
      state: directory      
  - name: Copy stack configuration files
    copy:
      src: files/docker-compose.yml
      dest: /home/ansible/uproot-nextcloud/
      mode: 0600
      owner: ansible
      group: ansible
  - name: configure nginx container
    copy:  
      src: files/nginx/nginx.conf
      dest: /home/ansible/uproot-nextcloud/nginx/
      owner: ansible
      group: ansible
  - name: insert environment vars
    template:
      src: env.j2
      dest: /home/ansible/uproot-nextcloud/.env
      mode: 0600
      owner: ansible
      group: ansible
  - name: Create and start services
    docker_compose:
      project_src: /home/ansible/uproot-nextcloud
    register: output
  