---
  # tasks file for nextcloud
  - name: Create a directory if it does not exist
    file:
      path: /home/ansible/uproot-nextcloud
      state: directory
  - name: create ddclient directoy
    file: 
      path: /home/ansible/uproot-nextcloud/ddclient
      state: directory
  - name: Copy stack configuration files
    copy:
      src: files/docker-compose.yml
      dest: /home/ansible/uproot-nextcloud/
  - name: configure ddclient
    template:
      src: ddclient.conf.j2
      dest: /home/ansible/uproot-nextcloud/ddclient/ddclient.conf
  - name: Create and start services
    docker_compose:
      project_src: /home/ansible/uproot-nextcloud
    register: output
  