route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 3h
  receiver: alertmanager-bot
receivers:
  - name: 'alertmananger-bot'
    webhook_configs:
    - send_resolved: true
      url: 'http://alertmanager-bot:8080'        