---
tasks:
- name: Ansible apt install packages
  apt:
    name:
      - htop
      - ncdu
      - bmon
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg-agent
      - wget
      - inotify-tools
      - fail2ban
      - cockpit
      - cockpit-docker
      - cockpit-packagekit
      - s3cmd
      - iotop
    state: present
    autoclean: yes