---
- name: Updating and Upgrading Packages
  apt:
    update_cache: yes
    upgrade: dist
- name: Installing Docker Dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
    update_cache: yes
    state: latest
    autoclean: yes
- name: Remove old version of Docker (if any)
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    autoclean: yes      
- name: Adding Docker repo GPG key to APT
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install python3 docker dependencies
  pip:
    name: docker
    executable: pip3
    state: latest  
- name: Installing Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - auditd
    update_cache: yes
    state: latest
- name: configuring auditd for docker
  copy:
    src: ../files/audit.rules
    dest: /etc/audit/rules.d/
    mode: 0640
    owner: root
    group: root
- name: configure docker daemon
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/
    owner: root
    group: root
- name: configure ufw before.init to remove existing rules
  blockinfile:
    path: /etc/ufw/before.init
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: stop\)
    block: |
      iptables -F DOCKER-USER || true
      iptables -A DOCKER-USER -j RETURN || true
      iptables -X ufw-user-input || true
- name: chmod /etc/ufw/before.init
  file:
    path: /etc/ufw/before.init
    state: touch
    mode: "a+x"
- name: configure ufw to work with DOCKER-USER chain name
  blockinfile:
    path: /etc/ufw/after.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK (docker-user)"
    block: |
      *filter
      :DOCKER-USER - [0:0]
      :ufw-user-input - [0:0]
      :ufw-after-logging-forward - [0:0]

      -A DOCKER-USER -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A DOCKER-USER -m conntrack --ctstate INVALID -j DROP
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j ufw-user-input
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j ufw-after-logging-forward
      -A DOCKER-USER -i {{ ansible_default_ipv4.interface }} -j DROP

      COMMIT
  